### ISSUE TITLE
Support for Marble and Limestone from other mods is broken

### ISSUE THREAD

**Issue by Keridos** [EoD/Chisel#5]
Would be nice to implement chiseling marble and Limestone from Underground Biomes Construct and marble from Project:Red.

**Comment by Solestis** [comment]
In our current version Project:Red marble already works, I just tested it.

I think the marble and limestone from Underground Biomes is also already supposed to work, but maybe the change to Underground Biomes Construct broke that. We will look into it.

**Comment by Keridos** [comment]
Is there a jenkins or some other place where you distribute compiled jars or do I have to compile it myself?

**Comment by EoD** [comment]
There is no jenkins yet as the code is changing a lot and no compatibility between our versions is guaranteed.

I uploaded the current build for you: https://github.com/EoD/Chisel/releases/

**Comment by Solestis** [comment]
I am currently working on updating the mod support as it seemed it was rather outdated, support for limestone and marble from Underground Biomes will be included in that update. =)

**Comment by Solestis** [comment]
This should be fixed in v1.5.8.5
